################################################################################
# PACKAGES #
################################################################################

# gen Utility ------------------------------------------------------------------
library(tidyverse)
library(pbapply)
library(data.table)
library(DT)
library(dplyr)
library(dbplyr)
library(pbapply)
library(stargazer)
library(rvest)
library(dbplyr)
library(DescTools)
library(aTSA)
library(BSDA)
library(jsonlite)
library(RSQLite)
library(rpart)
library(rpart.plot)
library(ranger)
library(caret)
library(naivebayes)
library(glmnet)
library(tidyquant)
library(RQuantLib)
library(derivmkts)
library(ggplot2)
library(reactable)
library(bdscale)
library('RSelenium')
library('XML')
library(EpsilonData)
library(EpsilonUtility)
